[package]
name = "http_pie"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.0"
clap = { version = "4.5.50", features = ["derive"] }
colored = "3.0.0"
jsonxf = "1.1"
mime = "0.3"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
